エンコーディング宣言の消去
Qman11010101/SO2MarketInfoBotForDiscord pull request #1
Opened 2019-06-09 13:41 UTC by Qman11010101

#エンコーディング宣言の消去
現在非推奨となっているエンコーディング宣言を消しました。Mergeよろしくお願いします

2019-06-09 13:53 UTC, YuzuRyo61 requested changes
SO2MarketInfo.pyの1行目にある
#!~は消したらあかん、Linuxで動作させるのに必要なんで
せめてそれだけ残してくれ

2019-06-09 14:03 UTC, Qman11010101 commented
了解、これでおｋ？

2019-06-10 04:00 UTC, YuzuRyo61 approved these changes
消すのはやむをえんが、動くのであれば問題はないか...

2019-06-10 04:02 UTC, merged

2019-06-10 06:13 UTC, Qman11010101 commented
終わったのでブランチ削除した