エラー処理追加 #36
Qman11010101/SO2MarketInfoBotForDiscord pull request #42
Opened 2019-07-03 13:54 UTC by Qman11010101

追加できてへんやんけーーーーーー！！！！！！！！

はい、今のままだとエラーが起きたらそれで終わりになってます…。なんで…
というわけで修正求む…

2019-07-03 13:55 UTC, Qman11010101 commented
未完成でPR投げるの良くない気はするけどわからなかったから助けを求める…

2019-07-03 14:30 UTC, YuzuRyo61 commented
> 追加できてへんやんけーーーーーー！！！！！！！！
> 
> はい、今のままだとエラーが起きたらそれで終わりになってます…。なんで…
> というわけで修正求む…

エラーログとかメッセージでている？

2019-07-03 14:35 UTC, YuzuRyo61 requested changes
修正いくつかあり

2019-07-03 14:35 UTC, YuzuRyo61 commented on SO2MI/Client.py
> +                    except AccessImpossibleError:
OSErrorでいい気がする・・・。

2019-07-03 14:35 UTC, YuzuRyo61 commented on SO2MI/Alias.py
> +        raise AccessImpossibleError("couldn't access to alias.json")
https://github.com/Qman11010101/SO2MarketInfoBotForDiscord/pull/42#issue-294180716

2019-07-03 14:35 UTC, YuzuRyo61 commented on SO2MI/Client.py
> -                    else:
これ消したらアカン
（try - exceptionはelseも使える）

2019-07-03 14:35 UTC, YuzuRyo61 commented on SO2MI/Exceptions.py
> +    pass
エンドライン・・・。

2019-07-03 14:35 UTC, YuzuRyo61 commented on SO2MI/Client.py
>                      res = removeAlias(msgParse[1])
これはtryの中に入れるべきなのでは

2019-07-03 16:31 UTC, Qman11010101 commented on SO2MI/Client.py
> -                    else:
でもこれ、ifのelseとは意味が違うんじゃね？else使ってもやることないんじゃ…？

2019-07-04 12:49 UTC, YuzuRyo61 commented on SO2MI/Client.py
> -                    else:
```python
try:
  # ここにメインのスクリプト
except ***:
  # エラーが起きたとき
else:
  # エラーが起きなかったとき
finally:
  # tryなどの中のスクリプトが終わった時に必ず実行されるとき
```

2019-07-04 13:05 UTC, YuzuRyo61 requested changes
以下のレビューを参照

2019-07-04 13:05 UTC, YuzuRyo61 commented on SO2MI/Client.py
> +                            await message.channel.send(f"エイリアスを追加しました。\n{msgParse[1]} → {msgParse[2]}")
やっぱりこうした方がいい
```python
try:
  addAlias(msgParse[1], msgParse[2]) # True返っても特にすることがないと判断し、返り値変数を設けないことに
except OSError:
  await message.channel.send("申し訳ありません。書き込みができません。")
except SameAliasNameExistError:
  await message.channel.send("既に登録されています。")
except NoItemError:
  await message.channel.send(f"{msgParse[2]}は存在しません。")
except NameDuplicationError:
  await message.channel.send(f"{msgParse[1]}というアイテムが既に存在しています。")
else:
  await message.channel.send(f"エイリアスを追加しました。\n{msgParse[1]} → {msgParse[2]}")
finally:
  return
```

2019-07-04 13:05 UTC, YuzuRyo61 commented on SO2MI/Client.py
> +                        if res:
```python
if removeAlias(msgParse[1]):
  #...
```
でも同じ結果が返る

2019-07-04 13:09 UTC, Qman11010101 commented on SO2MI/Client.py
> +                        if res:
まあそれはそうか

2019-07-04 13:12 UTC, Qman11010101 commented on SO2MI/Client.py
> +                            await message.channel.send(f"エイリアスを追加しました。\n{msgParse[1]} → {msgParse[2]}")
そうかこれfinallyでreturnさせられるのか

2019-07-04 13:12 UTC, YuzuRyo61 commented on SO2MI/Client.py
> +                            await message.channel.send(f"エイリアスを追加しました。\n{msgParse[1]} → {msgParse[2]}")
こうした方が無駄が少ないし見た目もちょっと良くなる

2019-07-04 13:13 UTC, Qman11010101 commented on SO2MI/Client.py
> +                            await message.channel.send(f"エイリアスを追加しました。\n{msgParse[1]} → {msgParse[2]}")
なるほど、理解理解

2019-07-04 13:14 UTC, Qman11010101 commented
うん、見た感じうまく動いてそうだ

2019-07-04 13:21 UTC, YuzuRyo61 approved these changes

2019-07-04 13:28 UTC, merged